<?php

   // DEBUG := TRUE | FALSE
   define(DEBUG , TRUE);
   
   // POP3 Accounts
   $POP_ACCOUNTS = array(
                      'php'   => 'php@evoknow.com:foobar:mail3.your-site.com',
                      'linux' => 'linux@evoknow.com:zoo123:mail3.your-site.com' 
                       );
  
  
   /* 
      ------------------------------------------------------------
      Logging section   
      
      LOGGING = TRUE | FALSE 
                enables or disables logging to file
      
      LOG_LEVEL = 1 | 2 
                  1 = minimal error logging
                  2 = extended logging
                  
      LOG_DIR = directory
                path where log file should be written
      
      Log filename syntax: %LOG_DIR%/<account>.log
      ------------------------------------------------------------
   */
      
   define(LOGGING,   TRUE); 
   define(LOG_LEVEL, 2);
   define(LOG_DIR ,  '/tmp');
   
                    
   // Each account can have its own allow/deny list
   $DENY_FROM['linux'] = array(
                                 'root2@.+',
                                 'root2@.+.?evoknow.com',
                                 'root@r2d2.evoknow.com'
                               );

   $DENY_FROM['php'] =   array(
                                 'mrfrog'                                 
                               );

   $ALLOW_FROM['linux'] = array(
                                'sheilakabir@evoknow.com',
                                'kabir@evoknow.com'
                                );

   $DENY_SUBJECT['php'] = array(
   					'/.*SEX/i',
   					'/.*FOO/i',
   					'/.*BAR/i'
                               );
   
   $APPLY_COMMON['php']   = TRUE;
   $APPLY_COMMON['linux'] = FALSE;
   
   
   $COMMON_DENY_SUBJECT     = array(
   					'/.*FREE MONEY/i',
   					'/.*PORN/i',
   					'/.*NUDE/i'
                               );
      
   $COMMON_DENY_FROM       = array(
   					'root',
   					'nobody',
   					'kabir'
                               );
                                           
   //List of headers considered for the above ALLOW\DENY FROM lists
   $FROM_HEADERS = array('/From:/i', '/Reply-To:/i' , '/Return-Path:/i');
   
?>
