<?php

  // Configuration file for Listing 1-4 

  // Set PHPLIB path
   $PHPLIB_DIR         = $_SERVER['DOCUMENT_ROOT'] . '/phplib';

  // Add PHPLIB path to PHP's include path
   ini_set( 'include_path', ':' . $PHPLIB_DIR . ':' . ini_get('include_path'));

  // Include the PHPLIB template class
  include('template.inc');

  // Setup this application's template directory path
  $TEMPLATE_DIR = $_SERVER['DOCUMENT_ROOT'] . '/ch1/templates';

  // Setup the output template filename
  $OUT_TEMPLATE = 'listing2out.html';


?>
