<?php

   // Turn on all error reporting
   error_reporting(E_ALL);

   // If you have installed framewirk directory in
   // a different directory than
   // %DocumentRoot%/framework, change the setting below.
   $APP_FRAMEWORK_DIR=$_SERVER['DOCUMENT_ROOT'] . '/charlene/framework';
   $PEAR             =$_SERVER['DOCUMENT_ROOT'] . '/charlene/pear';
   $PHPLIB           =$_SERVER['DOCUMENT_ROOT'] . '/charlene/phplib';

   // Insert the path in the PHP include_path so that PHP
   // looks for PEAR, PHPLIB and our application framework
   // classes in these directories
   ini_set( 'include_path', ':' .
         $PEAR .   ':' .
         $PHPLIB . ':' .
         $APP_FRAMEWORK_DIR . ':' .
         ini_get('include_path'));

   $AUTHENTICATION_URL = "/charlene/login/login.php";
   $LOGOUT_URL         = "/charlene/logout/logout.php";

   $APP_MENU           = '/home/home.php';

   $APPLICATION_NAME   = 'USER_MNGR';
   
   $XMAILER_ID         = 'Example User Manager Version 1.0';

   $DEFAULT_LANGUAGE   = 'US';
   $DEFAULT_DOMAIN     = 'example.com';
   $ROOT_PATH          = $_SERVER['DOCUMENT_ROOT'];
   $REL_ROOT_PATH      = '/charlene/user_mngr';
   $REL_APP_PATH       =  $REL_ROOT_PATH . '/apps';

   $TEMPLATE_DIR       = $ROOT_PATH     . $REL_APP_PATH . '/templates';
   $CLASS_DIR          = $ROOT_PATH     . $REL_APP_PATH . '/class';
   $REL_TEMPLATE_DIR   =  $REL_APP_PATH . '/templates/';

   
   require_once "user_mngr.errors";
   require_once "user_mngr.messages";
   require_once 'DB.php';
   require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';
   require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $USER_CLASS;
   require_once $TEMPLATE_CLASS;

   $MIN_USERNAME_SIZE= 3;
   $MIN_PASSWORD_SIZE= 3;
   $DUMMY_PASSWD = '1234567890';
   $ROOT_USER    = 'kabir@evoknow.com';
   $SECRET       = 916489;
   $CHAR_SET     = 'charset=iso-8859-1';

   // Application names

   $USERMNGR_MNGR              =  'user_mngr.php';
   $USERMNGR_FORGOTTEN_APP     =  'user_mngr_forgotten_pwd.php';
   $USERMNGR_CHANGE_PWD_APP    =  'user_mngr_passwd.php';

   /*  --------------START TABLE NAMES ---------------------- */
   //$APP_DB_URL        = 'mysql://root:foobar@localhost/auth';
   $APP_DB_URL      = array(
			    'phptype'  => 'mysql',
			    'username' => 'cwroblew',
			    'password' => 'g&06H3Da',
			    'hostspec' => 'localhost',
			    'database' => 'auth',
			    'new_link' => 'true'
			);
   $AUTH_DB_TBL       = 'Users';


   /*  --------------END TABLE NAMES ---------------------- */

   $STATUS_TEMPLATE              =  'usermngr_status.html';
   $USERMNGR_MENU_TEMPLATE       =  'usermngr_menu.html';
   $USERMNGR_USER_TEMPLATE       =  'usermngr_user_form.html';
   $USERMNGR_PWD_REQUEST_TEMPLATE=  'usermngr_forgotten_pwd.html';
   $USERMNGR_PWD_EMAIL_TEMPLATE  =  'usermngr_forgotten_pwd_email.html';
   $USERMNGR_PWD_RESET_TEMPLATE  =  'usermngr_pwd_reset.html';
   $USERMNGR_PWD_CHANGE_TEMPLATE =  'usermngr_pwd_change.html';

   $ADMINISTRATIVE_USER = 9;
   $STANDARD_USER = 1;
   $USER_TYPE = array('9' => 'Administrator', '1' => 'Standard User');

?>
