<?php


   // logout.conf

   error_reporting(E_ALL);
   
   $APP_FRAMEWORK_DIR=$_SERVER['DOCUMENT_ROOT'] . '/charlene/framework';
   $PEAR             =$_SERVER['DOCUMENT_ROOT'] . '/charlene/pear';
   $PHPLIB           =$_SERVER['DOCUMENT_ROOT'] . '/charlene/phplib';

   //$PATH = $PEAR_DIR . ':' . $PHPLIB_DIR . ':' . $APP_FRAMEWORK_DIR;

   ini_set( 'include_path', ':' .
         $PEAR .   ':' .
         $PHPLIB . ':' .
         $APP_FRAMEWORK_DIR . ':' .
         ini_get('include_path'));

   $PHP_SELF = $_SERVER["PHP_SELF"];


   $HOME_URL         = '/login/login.php';

   $APPLICATION_NAME = 'LOGOUT';
   $DEFAULT_LANGUAGE = 'US';


   //$AUTH_DB_URL      = 'mysql://root:foobar@localhost/auth';
   $AUTH_DB_URL      = array(
			    'phptype'  => 'mysql',
			    'username' => 'cwroblew',
			    'password' => 'g&06H3Da',
			    'hostspec' => 'localhost',
			    'database' => 'MortgageGuide',
			    'new_link' => 'true'
			);

   $AUTH_DB_TBL	     = 'Users';
   $ACTIVITY_LOG_TBL = 'ACTIVITY';   

   require_once "logout.errors";
   require_once "logout.messages";
   require_once 'DB.php';
   require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';
   require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $USER_CLASS;
   require_once $TEMPLATE_CLASS;


?>
