<?php

    define(DEBUG, FALSE);
 
    // Send email when mounted filesystem reaches 
    // percentage or more as given here
    $MAXSIZE['/'] = 30;
    $MAXSIZE['/usr'] = 50;
    $MAXSIZE['/mnt/win'] = 90;

    $MAIL_TEMPLATE = 'hdmonitor_mail.txt';

?>
