<?php


   // login.conf

   //extract($_GET);
   //extract($_POST);


   // Turn on all error reporting
   error_reporting(E_ALL);

   // If you have installed framewirk directory in
   // a different directory than
   // %DocumentRoot%/framework, change the setting below
   $APP_FRAMEWORK_DIR=$_SERVER['DOCUMENT_ROOT'] . '/charlene/framework';
   $PEAR             =$_SERVER['DOCUMENT_ROOT'] . '/charlene/pear';
   $PHPLIB           =$_SERVER['DOCUMENT_ROOT'] . '/charlene/phplib';

   // Insert the path in the PHP include_path so that PHP
   // looks for PEAR, PHPLIB and our application framework
   // classes in these directories
   ini_set( 'include_path', ':' .
         $PEAR .   ':' .
         $PHPLIB . ':' .
         $APP_FRAMEWORK_DIR . ':' .
         ini_get('include_path'));

   $PHP_SELF = $_SERVER["PHP_SELF"];

   $LOGIN_TEMPLATE    = 'login.html';

   $APPLICATION_NAME = 'LOGIN';
   $DEFAULT_LANGUAGE = 'US';

   //$AUTH_DB_URL      = 'mysql://cwroblew:g&06H3Da@localhost/MortgageGuide';
   $AUTH_DB_URL      = array(
			    'phptype'  => 'mysql',
			    'username' => 'cwroblew',
			    'password' => 'g&06H3Da',
			    'hostspec' => 'localhost',
			    'database' => 'MortgageGuide',
			    'new_link' => 'true'
			);
   $ACTIVITY_LOG_TBL = 'Activity';
   $AUTH_DB_TBL	     = 'Users';

   $MIN_USERNAME_SIZE= 3;
   $MIN_PASSWORD_SIZE= 3;
   $MAX_ATTEMPTS = 250;
   $FORGOTTEN_PASSWORD_APP = '/user_mngr/apps/user_mngr_forgotten_pwd.php';

   $APP_MENU       = '/';

   $TEMPLATE_DIR      = $_SERVER['DOCUMENT_ROOT'] . '/charlene/login/templates';
   $REL_TEMPLATE_DIR  = '/login/templates/';
   $WARNING_URL       = $TEMPLATE_DIR . '/warning.html';

   require_once "login.errors";
   require_once "login.messages";
   require_once 'DB.php';
   require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';

   require_once $APP_FRAMEWORK_DIR . '/' . $DEBUGGER_CLASS;


   require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $USER_CLASS;
   require_once $TEMPLATE_CLASS;
?>
