<?php


   define(DEBUG, TRUE);

   define(PASSWD_FILE, '/etc/passwd');

   $XMAILER = 'Reminder Version 1.0';

   // Reminder directory for users
   // Default: ~username/reminders
   define(USER_REMINDER_DIR, 'reminders');

   // Reminder configuration file for user
   // in user's reminder directory (%USER_REMINDER_DIR%/filename)
   // Default: %USER_REMINDER_DIR%/reminders.txt
   define(USER_REMINDER_FILE, 'reminders.txt');

?>
