<?php
/*
   
   This is the global form configuration that is loaded
   by submit.php.

   This configuraiton is in addition to the form specific configuration.
   The form specific configuration are automatically loaded based on
   the $KNOWN_FORMS field in this configuration.

   This configuration has standard configuration parameters
   needed for all forms.
*/

   error_reporting(E_ALL);
   // If you have installed PEAR packages in a different
   // directory than %DocumentRoot%/pear change the setting below.
   $PEAR_DIR           = $_SERVER['DOCUMENT_ROOT'] . '/pear';

   // If you have installed PHPLIB in a different
   // directory than %DocumentRoot%/phplib, change the setting below.
   $PHPLIB_DIR         = $_SERVER['DOCUMENT_ROOT'] . '/phplib';

   // If you have installed framewirk directory in a different
   // directory than %DocumentRoot%/framework, change the setting below.
   $APP_FRAMEWORK_DIR  = $_SERVER['DOCUMENT_ROOT'] . '/framework';


   $PATH = $PEAR_DIR . ':' . $PHPLIB_DIR . ':' . $APP_FRAMEWORK_DIR;

   ini_set( 'include_path', ':' . $PATH . ':' . ini_get('include_path'));


$DEFAULT_LANGUAGE   = 'US';
require_once "webforms.errors";
require_once 'DB.php';
require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';
require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
require_once $TEMPLATE_CLASS;

$ROOT_PATH          = $_SERVER['DOCUMENT_ROOT'];
$REL_ROOT_PATH      = '/webforms';
$REL_APP_PATH       = $REL_ROOT_PATH . '/apps';
$TEMPLATE_DIR       = $ROOT_PATH     . $REL_APP_PATH . '/templates';
$CLASS_DIR          = $ROOT_PATH     . $REL_APP_PATH . '/class';

$ACL_CLASS                     = $CLASS_DIR . '/class.ACL.php';
$DATA_VALIDATOR_CLASS          = $CLASS_DIR . '/class.DataValidator.php';
$FORM_SUBMISSION_CLASS         = $CLASS_DIR . '/class.FormSubmission.php';
$DATA_CLEANUP_CLASS            = $CLASS_DIR . '/class.DataCleanup.php';
$FORMDATA_CLASS                = $CLASS_DIR . '/class.FormData.php';

require_once $ACL_CLASS;
require_once $FORM_SUBMISSION_CLASS;
require_once $DATA_VALIDATOR_CLASS;
require_once $DATA_CLEANUP_CLASS;

// Application Name
define('APPLICATION_NAME', 'Web Form Processor');

// Form Database
define('FORM_DB_URL', 'mysql://root:foobar@localhost/WEBFORMS');


// Return values for form process()
define('MISSING_REQUIRED_VALUES', -1);
define('BAD_DATA', -2);
define('DATABASE_FAILURE', -3);
define('INVALID_FILE_SIZE', -4);


$KNOWN_FORMS = array(
                         'X9393948482339292929' => "askform.conf"
                    );


// conf files location from apps directory
define('FORM_CONF_FILE_DIR', 'site_forms');
define('REPORT_TEMPLATE', 'report.html');
define('ODD_COLOR', 'ffffee');
define('EVEN_COLOR', 'ffffcc');
define('DEFAULT_COLOR', 'FFFFFF');

define('MAX_YEAR', 2005);
define('MIN_YEAR', 2002);

define('REPORTER', 'webformsreporter.php');
define('CSV_EXPORTER', 'CSVExporter.php');
define('DOWNLOAD_TRACK_TBL', 'WEBFORMS_DL_TBL');

define('DOWNLOAD_TYPE_LATEST', 1);
define('DOWNLOAD_TYPE_ALL', 0);

?>
