<?php

   // Set this to the PEAR directory
   $PEAR_DIR = '/evoknow/intranet/htdocs/pear' ;

   ini_set( 'include_path', ':' . $PEAR_DIR . ':' . ini_get('include_path'));

   require_once "Console/Getopt.php";

   define(DEBUG, TRUE);

   define(NAMED_CONF, '/etc/named.conf');
   define(ZONE_DIR, '/var/named');
   define(ZONE_TEMPLATE_DIR, 'templates');
   define(ZONE_MASTER_TEMPLATE, 'named.master_zone.conf');
   define(DEFAULT_TEMPLATE, 'standard');

   $DOMAIN                 = 'yourcomapany.com';
   $PRIMARY_NAME_SERVER    = '192.168.0.11';
   $SECONDARY_NAME_SERVER  = '192.168.1.254';
   $PRI05_MAIL_SERVER      = '192.168.0.100';
   $PRI10_MAIL_SERVER      = '192.168.0.101';
   $WWW_SERVER_IP_ADDR     = '192.168.0.12';
   $FTP_SERVER_IP_ADDR     = '192.168.0.12';
   $WWW_SERVER_ALIAS       = 'apache.yourcompany.com';

?>
