<?php

function getNamedZoneConfig()
{

   $output = <<<MASTER_ZONE_NAMED_CONF

//
// Master zone configuration for $GLOBALS[ZONE]
//
zone "$GLOBALS[ZONE]" IN {
	type master;
	file "$GLOBALS[ZONE_FILE]";
	allow-update { none; };
};


MASTER_ZONE_NAMED_CONF;

   return $output;
}

?>

