<?php

   error_reporting(E_ALL);
   
   $PEAR_DIR           = $_SERVER['DOCUMENT_ROOT'] . '/pear' ;
   $PHPLIB_DIR         = $_SERVER['DOCUMENT_ROOT'] . '/phplib';
   $APP_FRAMEWORK_DIR  = $_SERVER['DOCUMENT_ROOT'] . '/framework';
   $PATH               = $PEAR_DIR . ':' . $PHPLIB_DIR . ':' . $APP_FRAMEWORK_DIR;

   ini_set( 'include_path', ':' . $PATH . ':' . ini_get('include_path'));

   $AUTHENTICATION_URL = "/login/login.php";
   $LOGOUT_URL         = "/logout/logout.php";

   $APPLICATION_NAME   = 'SURVEY';
   $XMAILER_ID         = 'Survey System Version 1.0';
   $DEFAULT_LANGUAGE   = 'US';
   $ROOT_PATH          = $_SERVER['DOCUMENT_ROOT'];
   $REL_ROOT_PATH      = '/survey_tool';
   $REL_APP_PATH       =  $REL_ROOT_PATH . '/apps';

   $REL_FORMS_DIR      = $REL_ROOT_PATH . '/forms';
   $UPLOAD_DIR         = $ROOT_PATH     . $REL_ROOT_PATH . '/uploads';
   $FORMS_DIR          = $ROOT_PATH     . $REL_FORMS_DIR;

   $TEMPLATE_DIR       = $ROOT_PATH     . $REL_APP_PATH . '/templates';
   $CLASS_DIR          = $ROOT_PATH     . $REL_APP_PATH . '/class';

   //Classes
   $SURVEY_LIST_CLASS     = $CLASS_DIR . '/' . 'class.SurveyList.php';
   $SURVEY_FORM_CLASS     = $CLASS_DIR . '/' . 'class.SurveyForm.php';
   $SURVEY_CLASS          = $CLASS_DIR . '/' . 'class.Survey.php';
   $SURVEY_RESPONSE_CLASS = $CLASS_DIR . '/' . 'class.SurveyResponse.php';
   $SURVEY_REPORT_CLASS   = $CLASS_DIR . '/' . 'class.SurveyReport.php';


   require_once "survey.errors";
   require_once "survey.messages";
   require_once 'DB.php';
   require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';
   require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
   require_once $TEMPLATE_CLASS;

   // Application names

   $SURVEY_MNGR           =  'survey_mngr.php';
   $SURVEY_FORM_MNGR      =  'survey_form_mngr.php';
   $SURVEY_LIST_MNGR      =  'survey_list_mngr.php';
   $SURVEY_RPT_MNGR       =  'survey_rpt_mngr.php';
   $SURVEY_EXEC_MNGR      =  'survey_exec_mngr.php';
   $SURVEY_RESPONSE_MNGR  =  'survey.php';

   $SURVEY_CLASS      = $CLASS_DIR . '/class.Survey.php';
   $REL_TEMPLATE_DIR  = $REL_APP_PATH . '/templates/';

   $SURVEY_DB_URL      = 'mysql://root:foobar@localhost/SURVEY';
   $MAX_DELIVERY_AT_A_TIME  = 1;
   $MAX_WAIT_PER_DELIVERY   = 5;

   /*  --------------START TABLE NAMES ---------------------- */

   $SURVEY_TBL                   = 'SURVEY';
   $SURVEY_LIST_TBL              = 'SURVEY_LIST';
   $SURVEY_LIST_DATA_TBL         = 'SURVEY_LIST_DATA';
   $SURVEY_FORM_TBL              = 'SURVEY_FORM';
   $SURVEY_RESPONSE_TBL          = 'SURVEY_RESPONSE';
   $SURVEY_FORM_FIELD_LBL_TBL    = 'SURVEY_FORM_FIELD_LBL';
   $SURVEY_RESPONSE_RECORD_TBL   = 'SURVEY_RESPONSE_RECORD';
   $SURVEY_EXECUTION_TBL         = 'SURVEY_EXECUTION';


   /*  --------------END TABLE NAMES ---------------------- */

   $STATUS_TEMPLATE            =  'survey_status.ihtml';
   $SURVEY_MENU_TEMPLATE       =  'survey_menu.ihtml';

   $SURVEY_ADD_LIST_TEMPLATE   =  'survey_add_list.ihtml';
   $SURVEY_ADD_FORM_TEMPLATE   =  'survey_add_form.ihtml';

   $SURVEY_ADD_LABEL_TEMPLATE  =  'survey_add_label.ihtml';

   $SURVEY_ADD_TEMPLATE        =  'survey_add.ihtml';
   $SURVEY_EXECUTION_TEMPLATE  =  'survey_execute.ihtml';

   $SURVEY_REPORT_TEMPLATE     =  'survey_report.ihtml';
   $SURVEY_POWERED_BY_TEMPLATE =  'powered_by.html';

   /* --------------------- REPORT --------------------*/
   $REPORT_EVEN_ROW_COLOR = '#ffccff';
   $REPORT_ODD_ROW_COLOR  = '#ccccff';
?>
