<?php

   // Set this to the PEAR directory
   $PEAR_DIR           = '/evoknow/intranet/htdocs/pear' ;

   ini_set( 'include_path', ':' . $PEAR_DIR . ':' . ini_get('include_path'));

   require_once "Console/Getopt.php";

   define(DEBUG, TRUE);

   $APACHE_INFO = array(
			 'user'      => 'httpd',
			 'group'     => 'httpd',
			 'path'      => '/usr/local/apache',
			 'bin_dir'   => 'bin',
			 'conf_dir'  => 'conf',
			 'conf_flie' => 'httpd.conf',
			 'server_bin'   => 'httpd',
			 'config_chk_opt'   => '-t -f',
			 'restart_opt'   => '-k restart',
                         'vhost_conf_dir' => 'conf/vhosts'
                       );


   $SYSTEM_INFO = array(
                         'passwd_file'   => '/etc/passwd',
                         'home_dir'      => '/home',
                         'min_passwd_length'   => 5,
                         'group_file'   => '/etc/group',
                         'server_ip'     => '192.168.0.11',
                         'useradd_bin'   => '/usr/sbin/useradd',
                         'www_partition' => '/www',
                         'permission'    => '0755',
                         'symlink_bin'   => '/bin/ln',
                         'symlink_opt'   => '-s',
                         'cp_bin'        => '/bin/cp',
                         'cp_opt'        => '-r',
                         'mkdir_bin'     => '/bin/mkdir',
                         'chmod_bin'     => '/bin/chmod',
                         'chown_bin'     => '/bin/chown'
                       );

  define(DEFAULT_ACCOUNT_TYPE , 'standard');
  define(DEFAULT_SYMLINK_USER_TO_WEBSITE , TRUE);

  //$TEMPLATE_DIR = '/www/vhosts';
  $TEMPLATE_DIR = 'vhosts';
  
  $ACCOUNT_TYPE['standard'] = array(
                                    vhost_template => 'std_vhost.conf',
                                    master_contents =>'std_contents.conf',
                                    mail_template  => 'std_vhost.mail',
                                    shell => '/bin/true'
                                   );

  $ACCOUNT_TYPE['gold'] = array(
                                vhost_template => 'gold_vhost.conf',
                                master_contents =>'gold_contents.conf',
                                mail_template  => 'gold_vhost.mail',
                                shell => '/bin/tcsh'
                               );

  $ACCOUNT_TYPE['platinum'] = array(
                                vhost_template => 'platinum_vhost.conf',
                                master_contents =>'platinum_contents.conf',
                                mail_template  => 'platinum_vhost.mail',
                                shell => '/bin/bash',
                               );
?>
