<?php

   function makeVirtualHost()
   {

      $www     = $GLOBALS[SYSTEM_INFO][www_partition];
      $ipAddr  = $GLOBALS[SYSTEM_INFO][server_ip];
      $server  = $GLOBALS[SERVER_NAME];

      $serverRoot = sprintf("%s/%s", $www, $server);
      $docRoot = sprintf("%s/%s/htdocs", $www, $server);
      $cgibin  = sprintf("%s/%s/cgibin", $www, $server);
      $logDir  = sprintf("%s/%s/logs", $www, $server);

      $vhostConfig = <<<STD_VHOST_CONF

      
      #
      # Automatied virtual host configuration for $GLOBALS[SERVER_NAME]
      #
      # Account Type: gold 
      #
      <VirtualHost $ipAddr>
   
         ServerName    $server
         DocumentRoot  "$docRoot"
         ErrorLog      "$logDir/errors.log"
         CustomLog     "$logDir/access.log" common

         # Enable PHP
         # php_admin_config engine on

        <Directory />
           
 
           # Disable retrival of .conf files
           <Files "*.conf">
              deny from all
           </Files>
        </Directory>

         # Enable CGI
         <Directory "$cgibin">
            Options ExecCGI -Indexes
         </Directory>

         Alias "/cgi-bin" "$cgibin/"

      </VirtualHost>
   

STD_VHOST_CONF;

      $output['config'] = $vhostConfig;
      $output['makedir'] = array(
                                 'SERVER_ROOT' => $serverRoot,
                                 'DOCUMENT_ROOT' => $docRoot, 
                                  'CGI_BIN' => $cgibin, 
                                 'LOG_DIR' => $logDir);

      return $output;

    }
?>
