<?php

   
    // Master contents for platinum account


   function copyContentsToSite($site = null)
   {

      $MASTER_CONTENTS_DIR = "vhosts/platinum/htdocs/*";

      $CP_BIN = $GLOBALS[SYSTEM_INFO][cp_bin];
      $CP_OPT = $GLOBALS[SYSTEM_INFO][cp_opt];

      $CHOWN_BIN = $GLOBALS[SYSTEM_INFO][chown_bin];
      $CHMOD_BIN = $GLOBALS[SYSTEM_INFO][chmod_bin];

      $user = $site[user];
      $group = $site[group];

      $docRoot = $site[DOCUMENT_ROOT];

      $cmd = "$CP_BIN $CP_OPT $MASTER_CONTENTS_DIR $docRoot";

      exec($cmd, $output, $status);

      $cmd = "$CHOWN_BIN -R $user:$group $docRoot";
      exec($cmd, $output, $status);

      $cmd = "$CHMOD_BIN -R 755 $docRoot";
      exec($cmd, $output, $status);

      return TRUE;
   }

?>
