<?php

   function makeVirtualHost()
   {

      $www     = $GLOBALS[SYSTEM_INFO][www_partition];
      $ipAddr  = $GLOBALS[SYSTEM_INFO][server_ip];
      $server  = $GLOBALS[SERVER_NAME];

      $serverRoot = sprintf("%s/%s", $www, $server);
      $docRoot = sprintf("%s/%s/htdocs", $www, $server);
      $logDir  = sprintf("%s/%s/logs", $www, $server);

      $vhostConfig = <<<STD_VHOST_CONF

      
      #
      # Automatied virtual host configuration for $GLOBALS[SERVER_NAME]
      #
      # Account Type: standard 
      #
      <VirtualHost $ipAddr>
   
         ServerName    $server
         DocumentRoot  "$docRoot"
         ErrorLog      "$logDir/errors.log"
         CustomLog     "$logDir/access.log" common

        <Directory />
           <Files "*.conf">
              deny from all
           </Files>
        </Directory>

      </VirtualHost>
   

STD_VHOST_CONF;

      $output['config'] = $vhostConfig;

      $output['makedir'] = array(
                                 'SERVER_ROOT' => $serverRoot, 
                                 'DOCUMENT_ROOT' => $docRoot, 
                                 'LOG_DIR' => $logDir);

      return $output;

    }
?>
