<?php
   // Turn on all error reporting
   error_reporting(E_ALL);
   
   // If you have installed PEAR packages in a different
   // directory than %DocumentRoot%/pear change the
   // setting below.
   $PEAR_DIR = $_SERVER['DOCUMENT_ROOT'] . '/pear' ;
   
   // If you have installed PHPLIB in a different
   // directory than %DocumentRoot%/phplib, change
   // the setting below.
   $PHPLIB_DIR = $_SERVER['DOCUMENT_ROOT'] . '/phplib';
   
   // If you have installed framewirk directory in
   // a different directory than
   // %DocumentRoot%/framework, change the setting below.
   $APP_FRAMEWORK_DIR=$_SERVER['DOCUMENT_ROOT'] . '/framework';
   
   // Relative URL to login script   
   $AUTHENTICATION_URL=  '/login/login.php';
   
   
   //Default language
   $DEFAULT_LANGUAGE = 'US';
        
   
   // Create a path consisting of the PEAR,
   // PHPLIB and our application framework
   // path ($APP_FRAMEWORK_DIR)
   $PATH = $PEAR_DIR . ':' .
           $PHPLIB_DIR . ':' .
           $APP_FRAMEWORK_DIR;
   
   // Insert the path in the PHP include_path so that PHP
   // looks for our PEAR, PHPLIB and application framework
   // classes in these directories
   ini_set( 'include_path', ':' .
            $PATH . ':' .
            ini_get('include_path'));
   
   // Now load the DB.php class from PEAR
   require_once 'DB.php';
   
   // Now load our DBI class from application framework

   require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';
   require_once $APP_FRAMEWORK_DIR . '/' . $DEBUGGER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $USER_CLASS;
   require_once $TEMPLATE_CLASS;
   
   // Load the Sample Application class
   require_once 'class.sampleApp.php';
   // Setup the database URL
   $SAMPLE_DB_URL = 'mysql://root:foobar@localhost/foobar';

?>
