<?php

 /*
       Expected Directory Structure

       %DocumentRoot%
       |
       +---pear
       |
       +---phplib
       |
       +---vote
           |
           +---apps
               |
               +---class
               |
               +---templates

   */

   // If you have installed PEAR packages in a different
   // directory than %DocumentRoot%/pear change the setting below.
   $PEAR_DIR           = $_SERVER['DOCUMENT_ROOT'] . '/pear' ;

   // If you have installed PHPLIB in a different
   // directory than %DocumentRoot%/phplib, change the setting below.
   $PHPLIB_DIR         = $_SERVER['DOCUMENT_ROOT'] . '/phplib';

   // If you have installed framewirk directory in a different
   // directory than %DocumentRoot%/framework, change the setting below.
   $APP_FRAMEWORK_DIR  = $_SERVER['DOCUMENT_ROOT'] . '/framework';

   $PATH = $PEAR_DIR . ':' . $PHPLIB_DIR . ':' . $APP_FRAMEWORK_DIR;

   ini_set( 'include_path', ':' . $PATH . ':' . ini_get('include_path'));


   $DEFAULT_LANGUAGE   = 'US';

   // If you have installed this application in a different
   // directory than %DocumentRoot%, chance the settings below.
   $ROOT_PATH          = $_SERVER['DOCUMENT_ROOT'];
   $REL_ROOT_PATH      = '/vote';

   $APPLICATION_NAME   = 'VOTE_TOOL';

   $REL_APP_PATH       = $REL_ROOT_PATH . '/apps';
   $TEMPLATE_DIR       = $ROOT_PATH     . $REL_APP_PATH . '/templates';
   $CLASS_DIR          = $ROOT_PATH     . $REL_APP_PATH . '/class';
   $REL_TEMPLATE_DIR   = $REL_APP_PATH  . '/templates/';

   // Change this database URL as needed
   $VOTE_DB_URL         = 'mysql://root:foobar@localhost/VOTE';
   
   /*  -------------- DEFINE CLASS NAMES --------------  */ 
   define('VOTE_CLASS', $CLASS_DIR . '/' .'class.Vote.php');
   
   /*  -------------- DEFINE TABLE NAMES --------------  */ 
   define('VOTE_TBL', 'VOTES');     
   
   /*  -------------- DEFINE TEMPLATE NAMES --------------  */ 
   $STATUS_TEMPLATE = 'vote_status.html';
         
   /*  -------------- DEFINE APPLICATION NAMES --------------  */ 
   define('VOTE_MNGR', 'vote.php');

   /*  -------------- DEFINE NUMBER OF SECONDS REPEAT VOTING IS NOT ALLOWED  --------------  */ 
   // Default: 60*60*24 = 1 day
   define('COOKIE_EXPIRATION_TIME', 86400);
   
   
   /*  --------------- REQUIRED FILES ----------------------*/
   require_once "vote.errors";
   require_once 'DB.php';
   require_once $APP_FRAMEWORK_DIR . '/' . 'constants.php';
   require_once $APP_FRAMEWORK_DIR . '/' . $APPLICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $ERROR_HANDLER_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $AUTHENTICATION_CLASS;
   require_once $APP_FRAMEWORK_DIR . '/' . $DBI_CLASS;
   require_once $TEMPLATE_CLASS;

   /* ------------------ POLL SPECIFIC CONFIGURATION ------------*/
   $choicesPerPoll = array(
                           //POLL ID      => NUMBER OF CHOICES
                                1         =>      4,
                                2         =>     7
                          );
?>
