<?php

    define(DEBUG, FALSE);
 
    $ALERT_CONDITIONS = array('RED', 'YELLOW', 'BLUE');

    // When system load has been in any of the following
    // alert condition for at least last 15 minutes
    // system is said to be at that alert level
    // Note: the order does not matter as loadmonitor
    // automatically chooses the highest alert level
    $ALERT['RED']      = 25;
    $ALERT['YELLOW']   = 15;
    $ALERT['BLUE']     = 5;

    $MAIL_TEMPLATE = 'loadmonitor_mail.txt';

     // Mail every n seconds when alert condition exists
     // Mail is sent only if the loadmonitor is run 
     // every n-1 seconds. Recommend running loadmonitor 
     // every 5 min and mail frequency 30 min (30 * 60 sec)
     // 0 = always send mail
    $MAIL_FREQUENCY = 1800;

     // Store when was the last time mail was sent
     // in a file so that we don't mailbomb the
     // admin
    $MAIL_CONTROL_FILE = '/tmp/loadmonitor.out';

    // Include this program output in mail
    $PS_BIN = 'top';
    $PS_OPT = ' -b -n 1';

?>
